# Generated by Django 2.1 on 2019-04-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='V2EX', max_length=20, null=True, verbose_name='站点标题')),
                ('bar_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='站点右侧边栏标题')),
                ('bar_desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='站点右侧边栏描述')),
            ],
            options={
                'verbose_name': '站点全局配置',
                'verbose_name_plural': '站点全局配置',
            },
        ),
    ]
