# Generated by Django 2.1 on 2019-04-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='comment_page_count',
            field=models.IntegerField(default=10, max_length=11, verbose_name='回复分页数'),
        ),
    ]
